### ISSUE TITLE
Daylight factor recipe fails when BSDF material is used

### ISSUE THREAD

**Issue by devngc** [ladybug-tools/lbt-recipes#39]
Hi @mostaphaRoudsari,

I believe I found a bug [here](https://discourse.ladybug.tools/t/lbt-aperture-bsdf/11846?u=devang). This happens when a bsdf is used as modifier. The results tuple from the popen is coming out empty.

Following is what I have done at my end before reporting this bug;

1. Tried a different .XML file (Same result)
2. Changed the child window location (Same result)
3. Looked at the debugging log from queenbee which I am sharing below. I believe that handler.py is trying to rename a file and it's not happening since the file is being used already. I figured this is something you can quickly fix.

            {0;0}
0. C:\Users\devan\simulation\sample_model_grid\Radiance\daylight-factor-inputs.json
1. 
2. DEBUG: Checking if LetDaylightFactorFly(_input_params={"model": "model", "radiance_parameters": "-ab 2", "sensor_count": 30, "sensor_grids": ["Room_9_7d664dd0"], "simulation_id": "daylight_factor", "simulation_folder": "C:/Users/devan/simulation/sample_model_grid/Radiance\\daylight_factor"}) is complete
DEBUG: Checking if _MainOrchestrator(_input_params={"model": "model", "radiance_parameters": "-ab 2", "sensor_count": 30, "sensor_grids": ["Room_9_7d664dd0"], "simulation_id": "daylight_factor", "simulation_folder": "C:/Users/devan/simulation/sample_model_grid/Radiance\\daylight_factor"}) is complete
INFO: Informed scheduler that task   LetDaylightFactorFly___model____model_601f3cb1a8   has status   PENDING
DEBUG: Checking if AggregateResults(_input_params={"model": "model", "params_folder": "__params", "radiance_parameters": "-ab 2", "sensor_grids": ["Room_9_7d664dd0"], "simulation_folder": "C:/Users/devan/simulation/sample_model_grid/Radiance\\daylight_factor", "sensor_count": 30, "simulation_id": "daylight_factor"}) is complete
INFO: Informed scheduler that task   _MainOrchestrator___model____model_601f3cb1a8   has status   PENDING
DEBUG: Checking if DaylightFactorRayTracing(_input_params={"model": "model", "params_folder": "__params", "radiance_parameters": "-ab 2", "sensor_grids": ["Room_9_7d664dd0"], "simulation_folder": "C:/Users/devan/simulation/sample_model_grid/Radiance\\daylight_factor", "sensor_count": 30, "simulation_id": "daylight_factor"}) is complete
INFO: Informed scheduler that task   AggregateResults___model____model_15895213f9   has status   PENDING
DEBUG: Checking if CreateOctree(_input_params={"model": "model", "params_folder": "__params", "radiance_parameters": "-ab 2", "sensor_grids": ["Room_9_7d664dd0"], "simulation_folder": "C:/Users/devan/simulation/sample_model_grid/Radiance\\daylight_factor", "sensor_count": 30, "simulation_id": "daylight_factor"}, black_out=default, include_aperture=include) is complete
INFO: Informed scheduler that task   DaylightFactorRayTracing___model____model_15895213f9   has status   PENDING
DEBUG: Checking if GenerateSky(_input_params={"model": "model", "params_folder": "__params", "radiance_parameters": "-ab 2", "sensor_grids": ["Room_9_7d664dd0"], "simulation_folder": "C:/Users/devan/simulation/sample_model_grid/Radiance\\daylight_factor", "sensor_count": 30, "simulation_id": "daylight_factor"}) is complete
INFO: Informed scheduler that task   CreateOctree___model____model_default_include_8e23235d17   has status   PENDING
INFO: Informed scheduler that task   GenerateSky___model____model_15895213f9   has status   PENDING
INFO: Done scheduling tasks
INFO: Running Worker with 8 processes
DEBUG: Asking scheduler for work...
DEBUG: Pending tasks: 6
DEBUG: Asking scheduler for work...
DEBUG: Done
DEBUG: There are no more tasks to run at this time
DEBUG: GenerateSky___model____model_15895213f9 is currently run by worker Worker(salt=199921065, workers=8, host=DESKTOP-SKE1C6S, username=devan, pid=10612)
DEBUG: Asking scheduler for work...
DEBUG: Done
DEBUG: There are no more tasks to run at this time
DEBUG: GenerateSky___model____model_15895213f9 is currently run by worker Worker(salt=199921065, workers=8, host=DESKTOP-SKE1C6S, username=devan, pid=10612)
INFO: Informed scheduler that task   GenerateSky___model____model_15895213f9   has status   DONE
DEBUG: Asking scheduler for work...
DEBUG: Pending tasks: 5
DEBUG: Asking scheduler for work...
DEBUG: Done
DEBUG: There are no more tasks to run at this time
DEBUG: CreateOctree___model____model_default_include_8e23235d17 is currently run by worker Worker(salt=199921065, workers=8, host=DESKTOP-SKE1C6S, username=devan, pid=10612)
DEBUG: Asking scheduler for work...
DEBUG: Done
DEBUG: There are no more tasks to run at this time
DEBUG: CreateOctree___model____model_default_include_8e23235d17 is currently run by worker Worker(salt=199921065, workers=8, host=DESKTOP-SKE1C6S, username=devan, pid=10612)
INFO: Informed scheduler that task   CreateOctree___model____model_default_include_8e23235d17   has status   DONE
DEBUG: Asking scheduler for work...
DEBUG: Pending tasks: 4
DEBUG: Asking scheduler for work...
DEBUG: Done
DEBUG: There are no more tasks to run at this time
DEBUG: DaylightFactorRayTracing___model____model_15895213f9 is currently run by worker Worker(salt=199921065, workers=8, host=DESKTOP-SKE1C6S, username=devan, pid=10612)
DEBUG: Checking if DaylightFactorRayTracingLoop(_input_params={"model": "model", "params_folder": "__params", "radiance_parameters": "-ab 2", "sensor_grids": ["Room_9_7d664dd0"], "simulation_folder": "C:/Users/devan/simulation/sample_model_grid/Radiance\\daylight_factor", "sensor_count": 30, "simulation_id": "daylight_factor"}, item="Room_9_7d664dd0") is complete
DEBUG: Checking if CreateOctree(_input_params={"model": "model", "params_folder": "__params", "radiance_parameters": "-ab 2", "sensor_grids": ["Room_9_7d664dd0"], "simulation_folder": "C:/Users/devan/simulation/sample_model_grid/Radiance\\daylight_factor", "sensor_count": 30, "simulation_id": "daylight_factor"}, black_out=default, include_aperture=include) is complete
INFO: Informed scheduler that task   DaylightFactorRayTracingLoop___model____model__Room_9_7d664dd0_8b7f4539bb   has status   PENDING
INFO: Informed scheduler that task   CreateOctree___model____model_default_include_8e23235d17   has status   DONE
INFO: Informed scheduler that task   DaylightFactorRayTracing___model____model_15895213f9   has status   PENDING
DEBUG: Asking scheduler for work...
DEBUG: Pending tasks: 5
DEBUG: Asking scheduler for work...
DEBUG: Done
DEBUG: There are no more tasks to run at this time
DEBUG: DaylightFactorRayTracingLoop___model____model__Room_9_7d664dd0_8b7f4539bb is currently run by worker Worker(salt=199921065, workers=8, host=DESKTOP-SKE1C6S, username=devan, pid=10612)
DEBUG: Checking if _RayTracingOrchestrator(_input_params={"simulation_folder": "C:/Users/devan/simulation/sample_model_grid/Radiance/daylight_factor/initial_results/Room_9_7d664dd0", "radiance_parameters": "-ab 2", "sensor_count": 30, "sensor_grid_name": "Room_9_7d664dd0", "octree_file": "C:/Users/devan/simulation/sample_model_grid/Radiance/daylight_factor/resources/scene.oct", "sensor_grid": "C:/Users/devan/simulation/sample_model_grid/Radiance/daylight_factor\\model/grid/Room_9_7d664dd0.pts"}) is complete
DEBUG: Checking if DaylightFactorSimulation(_input_params={"octree_file": "C:/Users/devan/simulation/sample_model_grid/Radiance/daylight_factor/resources/scene.oct", "params_folder": "__params", "radiance_parameters": "-ab 2", "sensor_grid": "C:/Users/devan/simulation/sample_model_grid/Radiance/daylight_factor\\model/grid/Room_9_7d664dd0.pts", "sensor_grid_name": "Room_9_7d664dd0", "simulation_folder": "C:/Users/devan/simulation/sample_model_grid/Radiance/daylight_factor/initial_results/Room_9_7d664dd0", "sensor_count": 30}) is complete
INFO: Informed scheduler that task   _RayTracingOrchestrator___simulation_fol_8ddce688b6   has status   PENDING
DEBUG: Checking if SplitGrid(_input_params={"octree_file": "C:/Users/devan/simulation/sample_model_grid/Radiance/daylight_factor/resources/scene.oct", "params_folder": "__params", "radiance_parameters": "-ab 2", "sensor_grid": "C:/Users/devan/simulation/sample_model_grid/Radiance/daylight_factor\\model/grid/Room_9_7d664dd0.pts", "sensor_grid_name": "Room_9_7d664dd0", "simulation_folder": "C:/Users/devan/simulation/sample_model_grid/Radiance/daylight_factor/initial_results/Room_9_7d664dd0", "sensor_count": 30}) is complete
INFO: Informed scheduler that task   DaylightFactorSimulation___octree_file____7c95f98169   has status   PENDING
INFO: Informed scheduler that task   SplitGrid___octree_file____7c95f98169   has status   PENDING
INFO: Informed scheduler that task   DaylightFactorRayTracingLoop___model____model__Room_9_7d664dd0_8b7f4539bb   has status   PENDING
DEBUG: Asking scheduler for work...
DEBUG: Pending tasks: 8
DEBUG: Asking scheduler for work...
DEBUG: Done
DEBUG: There are no more tasks to run at this time
DEBUG: SplitGrid___octree_file____7c95f98169 is currently run by worker Worker(salt=199921065, workers=8, host=DESKTOP-SKE1C6S, username=devan, pid=10612)
DEBUG: Asking scheduler for work...
DEBUG: Done
DEBUG: There are no more tasks to run at this time
DEBUG: SplitGrid___octree_file____7c95f98169 is currently run by worker Worker(salt=199921065, workers=8, host=DESKTOP-SKE1C6S, username=devan, pid=10612)
INFO: Informed scheduler that task   SplitGrid___octree_file____7c95f98169   has status   DONE
DEBUG: Asking scheduler for work...
DEBUG: Pending tasks: 7
DEBUG: Asking scheduler for work...
DEBUG: Done
DEBUG: There are no more tasks to run at this time
DEBUG: DaylightFactorSimulation___octree_file____7c95f98169 is currently run by worker Worker(salt=199921065, workers=8, host=DESKTOP-SKE1C6S, username=devan, pid=10612)
DEBUG: Checking if DaylightFactorSimulationLoop(_input_params={"octree_file": "C:/Users/devan/simulation/sample_model_grid/Radiance/daylight_factor/resources/scene.oct", "params_folder": "__params", "radiance_parameters": "-ab 2", "sensor_grid": "C:/Users/devan/simulation/sample_model_grid/Radiance/daylight_factor\\model/grid/Room_9_7d664dd0.pts", "sensor_grid_name": "Room_9_7d664dd0", "simulation_folder": "C:/Users/devan/simulation/sample_model_grid/Radiance/daylight_factor/initial_results/Room_9_7d664dd0", "sensor_count": 30}, fixed_radiance_parameters=-I -h, sky_illum=100000, item={"name": "grid_0000", "path": "grid_0000.pts", "full_path": "C:\\Users\\devan\\AppData\\Local\\Temp\\tmp2pg52tqz\\output\\grid_0000.pts", "count": 33}) is complete
DEBUG: Checking if SplitGrid(_input_params={"octree_file": "C:/Users/devan/simulation/sample_model_grid/Radiance/daylight_factor/resources/scene.oct", "params_folder": "__params", "radiance_parameters": "-ab 2", "sensor_grid": "C:/Users/devan/simulation/sample_model_grid/Radiance/daylight_factor\\model/grid/Room_9_7d664dd0.pts", "sensor_grid_name": "Room_9_7d664dd0", "simulation_folder": "C:/Users/devan/simulation/sample_model_grid/Radiance/daylight_factor/initial_results/Room_9_7d664dd0", "sensor_count": 30}) is complete
INFO: Informed scheduler that task   DaylightFactorSimulationLoop___octree_file_____I__h___name____grid_0_cdf647a8a2   has status   PENDING
INFO: Informed scheduler that task   SplitGrid___octree_file____7c95f98169   has status   DONE
DEBUG: Checking if DaylightFactorSimulationLoop(_input_params={"octree_file": "C:/Users/devan/simulation/sample_model_grid/Radiance/daylight_factor/resources/scene.oct", "params_folder": "__params", "radiance_parameters": "-ab 2", "sensor_grid": "C:/Users/devan/simulation/sample_model_grid/Radiance/daylight_factor\\model/grid/Room_9_7d664dd0.pts", "sensor_grid_name": "Room_9_7d664dd0", "simulation_folder": "C:/Users/devan/simulation/sample_model_grid/Radiance/daylight_factor/initial_results/Room_9_7d664dd0", "sensor_count": 30}, fixed_radiance_parameters=-I -h, sky_illum=100000, item={"name": "grid_0001", "path": "grid_0001.pts", "full_path": "C:\\Users\\devan\\AppData\\Local\\Temp\\tmp2pg52tqz\\output\\grid_0001.pts", "count": 33}) is complete
DEBUG: Checking if SplitGrid(_input_params={"octree_file": "C:/Users/devan/simulation/sample_model_grid/Radiance/daylight_factor/resources/scene.oct", "params_folder": "__params", "radiance_parameters": "-ab 2", "sensor_grid": "C:/Users/devan/simulation/sample_model_grid/Radiance/daylight_factor\\model/grid/Room_9_7d664dd0.pts", "sensor_grid_name": "Room_9_7d664dd0", "simulation_folder": "C:/Users/devan/simulation/sample_model_grid/Radiance/daylight_factor/initial_results/Room_9_7d664dd0", "sensor_count": 30}) is complete
INFO: Informed scheduler that task   DaylightFactorSimulationLoop___octree_file_____I__h___name____grid_0_b8d7660e78   has status   PENDING
INFO: Informed scheduler that task   SplitGrid___octree_file____7c95f98169   has status   DONE
DEBUG: Checking if DaylightFactorSimulationLoop(_input_params={"octree_file": "C:/Users/devan/simulation/sample_model_grid/Radiance/daylight_factor/resources/scene.oct", "params_folder": "__params", "radiance_parameters": "-ab 2", "sensor_grid": "C:/Users/devan/simulation/sample_model_grid/Radiance/daylight_factor\\model/grid/Room_9_7d664dd0.pts", "sensor_grid_name": "Room_9_7d664dd0", "simulation_folder": "C:/Users/devan/simulation/sample_model_grid/Radiance/daylight_factor/initial_results/Room_9_7d664dd0", "sensor_count": 30}, fixed_radiance_parameters=-I -h, sky_illum=100000, item={"name": "grid_0002", "path": "grid_0002.pts", "full_path": "C:\\Users\\devan\\AppData\\Local\\Temp\\tmp2pg52tqz\\output\\grid_0002.pts", "count": 34}) is complete
DEBUG: Checking if SplitGrid(_input_params={"octree_file": "C:/Users/devan/simulation/sample_model_grid/Radiance/daylight_factor/resources/scene.oct", "params_folder": "__params", "radiance_parameters": "-ab 2", "sensor_grid": "C:/Users/devan/simulation/sample_model_grid/Radiance/daylight_factor\\model/grid/Room_9_7d664dd0.pts", "sensor_grid_name": "Room_9_7d664dd0", "simulation_folder": "C:/Users/devan/simulation/sample_model_grid/Radiance/daylight_factor/initial_results/Room_9_7d664dd0", "sensor_count": 30}) is complete
INFO: Informed scheduler that task   DaylightFactorSimulationLoop___octree_file_____I__h___name____grid_0_2c2b57f5c6   has status   PENDING
INFO: Informed scheduler that task   SplitGrid___octree_file____7c95f98169   has status   DONE
INFO: Informed scheduler that task   DaylightFactorSimulation___octree_file____7c95f98169   has status   PENDING
DEBUG: Asking scheduler for work...
DEBUG: Pending tasks: 10
DEBUG: Asking scheduler for work...
DEBUG: Pending tasks: 9
DEBUG: Asking scheduler for work...
DEBUG: Pending tasks: 8
DEBUG: Asking scheduler for work...
DEBUG: Done
DEBUG: There are no more tasks to run at this time
DEBUG: DaylightFactorSimulationLoop___octree_file_____I__h___name____grid_0_cdf647a8a2 is currently run by worker Worker(salt=199921065, workers=8, host=DESKTOP-SKE1C6S, username=devan, pid=10612)
DEBUG: DaylightFactorSimulationLoop___octree_file_____I__h___name____grid_0_b8d7660e78 is currently run by worker Worker(salt=199921065, workers=8, host=DESKTOP-SKE1C6S, username=devan, pid=10612)
DEBUG: DaylightFactorSimulationLoop___octree_file_____I__h___name____grid_0_2c2b57f5c6 is currently run by worker Worker(salt=199921065, workers=8, host=DESKTOP-SKE1C6S, username=devan, pid=10612)
DEBUG: Asking scheduler for work...
DEBUG: Done
DEBUG: There are no more tasks to run at this time
DEBUG: DaylightFactorSimulationLoop___octree_file_____I__h___name____grid_0_cdf647a8a2 is currently run by worker Worker(salt=199921065, workers=8, host=DESKTOP-SKE1C6S, username=devan, pid=10612)
DEBUG: DaylightFactorSimulationLoop___octree_file_____I__h___name____grid_0_b8d7660e78 is currently run by worker Worker(salt=199921065, workers=8, host=DESKTOP-SKE1C6S, username=devan, pid=10612)
DEBUG: DaylightFactorSimulationLoop___octree_file_____I__h___name____grid_0_2c2b57f5c6 is currently run by worker Worker(salt=199921065, workers=8, host=DESKTOP-SKE1C6S, username=devan, pid=10612)
INFO: Informed scheduler that task   DaylightFactorSimulationLoop___octree_file_____I__h___name____grid_0_cdf647a8a2   has status   DONE
DEBUG: Asking scheduler for work...
DEBUG: Done
DEBUG: There are no more tasks to run at this time
DEBUG: DaylightFactorSimulationLoop___octree_file_____I__h___name____grid_0_b8d7660e78 is currently run by worker Worker(salt=199921065, workers=8, host=DESKTOP-SKE1C6S, username=devan, pid=10612)
DEBUG: DaylightFactorSimulationLoop___octree_file_____I__h___name____grid_0_2c2b57f5c6 is currently run by worker Worker(salt=199921065, workers=8, host=DESKTOP-SKE1C6S, username=devan, pid=10612)
INFO: Informed scheduler that task   DaylightFactorSimulationLoop___octree_file_____I__h___name____grid_0_b8d7660e78   has status   DONE
DEBUG: Asking scheduler for work...
DEBUG: Done
DEBUG: There are no more tasks to run at this time
DEBUG: DaylightFactorSimulationLoop___octree_file_____I__h___name____grid_0_2c2b57f5c6 is currently run by worker Worker(salt=199921065, workers=8, host=DESKTOP-SKE1C6S, username=devan, pid=10612)
INFO: Informed scheduler that task   DaylightFactorSimulationLoop___octree_file_____I__h___name____grid_0_2c2b57f5c6   has status   DONE
DEBUG: Asking scheduler for work...
DEBUG: Pending tasks: 7
DEBUG: Asking scheduler for work...
DEBUG: Done
DEBUG: There are no more tasks to run at this time
DEBUG: DaylightFactorSimulation___octree_file____7c95f98169 is currently run by worker Worker(salt=199921065, workers=8, host=DESKTOP-SKE1C6S, username=devan, pid=10612)
INFO: Informed scheduler that task   DaylightFactorSimulation___octree_file____7c95f98169   has status   DONE
DEBUG: Asking scheduler for work...
DEBUG: Pending tasks: 6
DEBUG: Asking scheduler for work...
DEBUG: Done
DEBUG: There are no more tasks to run at this time
DEBUG: _RayTracingOrchestrator___simulation_fol_8ddce688b6 is currently run by worker Worker(salt=199921065, workers=8, host=DESKTOP-SKE1C6S, username=devan, pid=10612)
INFO: Informed scheduler that task   _RayTracingOrchestrator___simulation_fol_8ddce688b6   has status   DONE
DEBUG: Asking scheduler for work...
DEBUG: Pending tasks: 5
DEBUG: Asking scheduler for work...
DEBUG: Done
DEBUG: There are no more tasks to run at this time
DEBUG: DaylightFactorRayTracingLoop___model____model__Room_9_7d664dd0_8b7f4539bb is currently run by worker Worker(salt=199921065, workers=8, host=DESKTOP-SKE1C6S, username=devan, pid=10612)
INFO: Informed scheduler that task   DaylightFactorRayTracingLoop___model____model__Room_9_7d664dd0_8b7f4539bb   has status   DONE
DEBUG: Asking scheduler for work...
DEBUG: Pending tasks: 4
DEBUG: Asking scheduler for work...
DEBUG: Done
DEBUG: There are no more tasks to run at this time
DEBUG: DaylightFactorRayTracing___model____model_15895213f9 is currently run by worker Worker(salt=199921065, workers=8, host=DESKTOP-SKE1C6S, username=devan, pid=10612)
INFO: Informed scheduler that task   DaylightFactorRayTracing___model____model_15895213f9   has status   DONE
DEBUG: Asking scheduler for work...
DEBUG: Pending tasks: 3
DEBUG: Asking scheduler for work...
DEBUG: Done
DEBUG: There are no more tasks to run at this time
DEBUG: AggregateResults___model____model_15895213f9 is currently run by worker Worker(salt=199921065, workers=8, host=DESKTOP-SKE1C6S, username=devan, pid=10612)
DEBUG: Checking if AggregateResultsLoop(_input_params={"model": "model", "params_folder": "__params", "radiance_parameters": "-ab 2", "sensor_grids": ["Room_9_7d664dd0"], "simulation_folder": "C:/Users/devan/simulation/sample_model_grid/Radiance\\daylight_factor", "sensor_count": 30, "simulation_id": "daylight_factor"}, item="Room_9_7d664dd0") is complete
DEBUG: Checking if DaylightFactorRayTracing(_input_params={"model": "model", "params_folder": "__params", "radiance_parameters": "-ab 2", "sensor_grids": ["Room_9_7d664dd0"], "simulation_folder": "C:/Users/devan/simulation/sample_model_grid/Radiance\\daylight_factor", "sensor_count": 30, "simulation_id": "daylight_factor"}) is complete
INFO: Informed scheduler that task   AggregateResultsLoop___model____model__Room_9_7d664dd0_8b7f4539bb   has status   PENDING
INFO: Informed scheduler that task   DaylightFactorRayTracing___model____model_15895213f9   has status   DONE
INFO: Informed scheduler that task   AggregateResults___model____model_15895213f9   has status   PENDING
DEBUG: Asking scheduler for work...
DEBUG: Pending tasks: 4
DEBUG: Asking scheduler for work...
DEBUG: Done
DEBUG: There are no more tasks to run at this time
DEBUG: AggregateResultsLoop___model____model__Room_9_7d664dd0_8b7f4539bb is currently run by worker Worker(salt=199921065, workers=8, host=DESKTOP-SKE1C6S, username=devan, pid=10612)
DEBUG: Asking scheduler for work...
DEBUG: Done
DEBUG: There are no more tasks to run at this time
DEBUG: AggregateResultsLoop___model____model__Room_9_7d664dd0_8b7f4539bb is currently run by worker Worker(salt=199921065, workers=8, host=DESKTOP-SKE1C6S, username=devan, pid=10612)
b'--- Logging error ---\r\nTraceback (most recent call last):\r\n  File "c:\\users\\devan\\ladybug_tools\\python\\lib\\site-packages\\honeybee_radiance\\cli\\grid.py", line 88, in merge_grid\r\n    first_line = next(inf)\r\nStopIteration\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nTraceback (most recent call last):\r\n  File "c:\\users\\devan\\ladybug_tools\\python\\lib\\logging\\handlers.py", line 70, in emit\r\n    self.doRollover()\r\n  File "c:\\users\\devan\\ladybug_tools\\python\\lib\\logging\\handlers.py", line 394, in doRollover\r\n    self.rotate(self.baseFilename, dfn)\r\n  File "c:\\users\\devan\\ladybug_tools\\python\\lib\\logging\\handlers.py", line 111, in rotate\r\n    os.rename(source, dest)\r\nPermissionError: [WinError 32] The process cannot access the file because it is being used by another process: \'C:\\\\Users\\\\devan\\\\.honeybee\\\\honeybee.log\' -> \'C:\\\\Users\\\\devan\\\\.honeybee\\\\honeybee.log.2020-10-28\'\r\nCall stack:\r\n  File "c:\\users\\devan\\ladybug_tools\\python\\lib\\runpy.py", line 193, in _run_module_as_main\r\n    "__main__", mod_spec)\r\n  File "c:\\users\\devan\\ladybug_tools\\python\\lib\\runpy.py", line 85, in _run_code\r\n    exec(code, run_globals)\r\n  File "c:\\users\\devan\\ladybug_tools\\python\\Scripts\\honeybee-radiance.exe\\__main__.py", line 7, in <module>\r\n    sys.exit(radiance())\r\n  File "c:\\users\\devan\\ladybug_tools\\python\\lib\\site-packages\\click\\core.py", line 829, in __call__\r\n    return self.main(*args, **kwargs)\r\n  File "c:\\users\\devan\\ladybug_tools\\python\\lib\\site-packages\\click\\core.py", line 782, in main\r\n    rv = self.invoke(ctx)\r\n  File "c:\\users\\devan\\ladybug_tools\\python\\lib\\site-packages\\click\\core.py", line 1259, in invoke\r\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\r\n  File "c:\\users\\devan\\ladybug_tools\\python\\lib\\site-packages\\click\\core.py", line 1259, in invoke\r\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\r\n  File "c:\\users\\devan\\ladybug_tools\\python\\lib\\site-packages\\click\\core.py", line 1066, in invoke\r\n    return ctx.invoke(self.callback, **ctx.params)\r\n  File "c:\\users\\devan\\ladybug_tools\\python\\lib\\site-packages\\click\\core.py", line 610, in invoke\r\n    return callback(*args, **kwargs)\r\n  File "c:\\users\\devan\\ladybug_tools\\python\\lib\\site-packages\\honeybee_radiance\\cli\\grid.py", line 102, in merge_grid\r\n    _logger.exception(\'Failed to merge grid files.\')\r\nMessage: \'Failed to merge grid files.\'\r\nArguments: ()\r\nhoneybee_radiance.cli.grid - ERROR - Failed to merge grid files.\r\nTraceback (most recent call last):\r\n  File "c:\\users\\devan\\ladybug_tools\\python\\lib\\site-packages\\honeybee_radiance\\cli\\grid.py", line 88, in merge_grid\r\n    first_line = next(inf)\r\nStopIteration\r\n'
[pid 12032] Worker Worker(salt=199921065, workers=8, host=DESKTOP-SKE1C6S, username=devan, pid=10612) failed    AggregateResultsLoop(_input_params={"model": "model", "params_folder": "__params", "radiance_parameters": "-ab 2", "sensor_grids": ["Room_9_7d664dd0"], "simulation_folder": "C:/Users/devan/simulation/sample_model_grid/Radiance\\daylight_factor", "sensor_count": 30, "simulation_id": "daylight_factor"}, item="Room_9_7d664dd0")
Traceback (most recent call last):
  File "c:\users\devan\ladybug_tools\python\lib\site-packages\luigi\worker.py", line 191, in run
    new_deps = self._run_get_new_deps()
  File "c:\users\devan\ladybug_tools\python\lib\site-packages\luigi\worker.py", line 133, in _run_get_new_deps
    task_gen = self.task.run()
  File "c:\users\devan\ladybug_tools\python\lib\site-packages\queenbee_luigi\luigi_util.py", line 296, in run
    raise RuntimeError(errors)
RuntimeError: b'--- Logging error ---\r\nTraceback (most recent call last):\r\n  File "c:\\users\\devan\\ladybug_tools\\python\\lib\\site-packages\\honeybee_radiance\\cli\\grid.py", line 88, in merge_grid\r\n    first_line = next(inf)\r\nStopIteration\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nTraceback (most recent call last):\r\n  File "c:\\users\\devan\\ladybug_tools\\python\\lib\\logging\\handlers.py", line 70, in emit\r\n    self.doRollover()\r\n  File "c:\\users\\devan\\ladybug_tools\\python\\lib\\logging\\handlers.py", line 394, in doRollover\r\n    self.rotate(self.baseFilename, dfn)\r\n  File "c:\\users\\devan\\ladybug_tools\\python\\lib\\logging\\handlers.py", line 111, in rotate\r\n    os.rename(source, dest)\r\nPermissionError: [WinError 32] The process cannot access the file because it is being used by another process: \'C:\\\\Users\\\\devan\\\\.honeybee\\\\honeybee.log\' -> \'C:\\\\Users\\\\devan\\\\.honeybee\\\\honeybee.log.2020-10-28\'\r\nCall stack:\r\n  File "c:\\users\\devan\\ladybug_tools\\python\\lib\\runpy.py", line 193, in _run_module_as_main\r\n    "__main__", mod_spec)\r\n  File "c:\\users\\devan\\ladybug_tools\\python\\lib\\runpy.py", line 85, in _run_code\r\n    exec(code, run_globals)\r\n  File "c:\\users\\devan\\ladybug_tools\\python\\Scripts\\honeybee-radiance.exe\\__main__.py", line 7, in <module>\r\n    sys.exit(radiance())\r\n  File "c:\\users\\devan\\ladybug_tools\\python\\lib\\site-packages\\click\\core.py", line 829, in __call__\r\n    return self.main(*args, **kwargs)\r\n  File "c:\\users\\devan\\ladybug_tools\\python\\lib\\site-packages\\click\\core.py", line 782, in main\r\n    rv = self.invoke(ctx)\r\n  File "c:\\users\\devan\\ladybug_tools\\python\\lib\\site-packages\\click\\core.py", line 1259, in invoke\r\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\r\n  File "c:\\users\\devan\\ladybug_tools\\python\\lib\\site-packages\\click\\core.py", line 1259, in invoke\r\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\r\n  File "c:\\users\\devan\\ladybug_tools\\python\\lib\\site-packages\\click\\core.py", line 1066, in invoke\r\n    return ctx.invoke(self.callback, **ctx.params)\r\n  File "c:\\users\\devan\\ladybug_tools\\python\\lib\\site-packages\\click\\core.py", line 610, in invoke\r\n    return callback(*args, **kwargs)\r\n  File "c:\\users\\devan\\ladybug_tools\\python\\lib\\site-packages\\honeybee_radiance\\cli\\grid.py", line 102, in merge_grid\r\n    _logger.exception(\'Failed to merge grid files.\')\r\nMessage: \'Failed to merge grid files.\'\r\nArguments: ()\r\nhoneybee_radiance.cli.grid - ERROR - Failed to merge grid files.\r\nTraceback (most recent call last):\r\n  File "c:\\users\\devan\\ladybug_tools\\python\\lib\\site-packages\\honeybee_radiance\\cli\\grid.py", line 88, in merge_grid\r\n    first_line = next(inf)\r\nStopIteration\r\n'
Exception ignored in: <finalize object at 0x133ee8ef5a0; dead>
Traceback (most recent call last):
  File "c:\users\devan\ladybug_tools\python\lib\weakref.py", line 572, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "c:\users\devan\ladybug_tools\python\lib\tempfile.py", line 797, in _cleanup
    _shutil.rmtree(name)
  File "c:\users\devan\ladybug_tools\python\lib\shutil.py", line 516, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "c:\users\devan\ladybug_tools\python\lib\shutil.py", line 404, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "c:\users\devan\ladybug_tools\python\lib\shutil.py", line 402, in _rmtree_unsafe
    os.rmdir(path)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\devan\\AppData\\Local\\Temp\\tmplcjzyk9j'
INFO: Informed scheduler that task   AggregateResultsLoop___model____model__Room_9_7d664dd0_8b7f4539bb   has status   FAILED
DEBUG: Asking scheduler for work...
DEBUG: Done
DEBUG: There are no more tasks to run at this time
DEBUG: There are 4 pending tasks possibly being run by other workers
DEBUG: There are 4 pending tasks unique to this worker
DEBUG: There are 4 pending tasks last scheduled by this worker
INFO: Worker Worker(salt=199921065, workers=8, host=DESKTOP-SKE1C6S, username=devan, pid=10612) was stopped. Shutting down Keep-Alive thread
INFO: 
===== Luigi Execution Summary =====

Scheduled 15 tasks of which:
* 10 ran successfully:
    - 1 CreateOctree(...)
    - 1 DaylightFactorRayTracing(...)
    - 1 DaylightFactorRayTracingLoop(...)
    - 1 DaylightFactorSimulation(...)
    - 3 DaylightFactorSimulationLoop(...)
    ...
* 1 failed:
    - 1 AggregateResultsLoop(...)
* 4 were left pending, among these:
    * 1 were missing external dependencies:
        - 1 AggregateResults(...)
    * 2 had missing dependencies:
        - 1 LetDaylightFactorFly(...)
        - 1 _MainOrchestrator(...)
    * 1 was not granted run permission by the scheduler:
        - 1 AggregateResults(...)

This progress looks :( because there were failed tasks

===== Luigi Execution Summary =====

3.

**Comment by chriswmackey** [comment]
This has been addressed!
